export const SINGUP_LOADING = 'SINGUP_LOADING';
export const SINGUP_FAIL = 'SINGUP_FAIL';
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS';

export const SINGIN_LOADING = 'SINGIN_LOADING';
export const SINGIN_FAIL = 'SINGIN_FAIL';
export const SINGIN_SUCCESS = 'SINGIN_SUCCESS';
